apiVersion: v1
kind: Secret
metadata:
  name: core-secret
  namespace: default
type: Opaque
# Lembre-se que todos os valores utilizados aqui devem ser
# transformados em base64.
data:
  # A app key utilizada pelo Adonis para encriptação interna
  # é um dado sensível. Por isso a colocamos em um secret:
  APP_KEY: ''
  # Usuário e senha do banco de dados. Em produção você deve
  # utilizar um valor mais seguro.
  PG_USER: ''
  PG_PASSWORD: ''
  # Abaixo temos o "secret" do cliente dentro do Keycloak.
  # Em produção recomenda-se gerar um novo secret na interface
  # do Keycloak antes de utilizá-lo aqui. Caso você gere um
  # novo secret no Keycloak, lembre-se de convertê-lo em
  # base64 antes de colocá-lo aqui.
  KEYCLOAK_CLIENT_SECRET: ''
  # Use os dados do Mailtrap abaixo (lembre-se de convertê-los
  # em base64).
  SMTP_USERNAME: ''
  SMTP_PASSWORD: ''
